tasks:
  - class: DecodeText
  - class: DumpBeams
    params:
      file: logs/beams.npz
model_dir: data/filtered
model_params:
  inference.beam_search.beam_width: 5
input_pipeline:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - data/twitter_test_bpe_sources.txt