model_params:
  vocab_source: data/vocab_test.txt
  vocab_target: data/vocab_test.txt
input_pipeline_train:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - data/twitter_test_bpe_sources.txt
    target_files:
      - data/twitter_test_bpe_targets.txt
input_pipeline_dev:
  class: ParallelTextInputPipeline
  params:
      source_files:
        - data/twitter_test_bpe_sources.txt
      target_files:
        - data/twitter_test_bpe_targets.txt
batch_size: 32
train_steps: 10000
output_dir: data/map