tasks:
  - class: DumpAttention
    params:
      output_dir: logs/dump_attention_filtered
model_dir: data/filtered
input_pipeline:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - data/twitter_test_bpe_sources.txt