model_params:
  vocab_source: data/toy/vocab.sources.txt
  vocab_target: data/toy/vocab.targets.txt
input_pipeline_train:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - data/toy/reverse_sources.txt
    target_files:
      - data/toy/reverse_targets.txt
input_pipeline_dev:
  class: ParallelTextInputPipeline
  params:
      source_files:
        - data/toy/reverse_sources_dev.txt
      target_files:
        - data/toy/reverse_targets_dev.txt
batch_size: 32
train_steps: 1000
output_dir: data/toy