tasks:
  - class: DumpAttention
    params:
      output_dir: logs/dump_attention_toy
model_dir: data/toy
input_pipeline:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - data/toy/reverse_sources_test.txt